### ISSUE TITLE
AO486 MiSTer - Secret of Monkey Island - SCUMM Bar Door Opening Sound is Incorrect

### ISSUE THREAD

**Issue by hubby4** [gtaylormb/opl3_fpga#47]
This game supports Adlib only for FM, so I doubt this is a problem with the DSP. 

You can hear how the SCUMM Bar door opening sounds on a real Adlib soundcard by going to the 4 min 26 sec mark in this video.

https://www.youtube.com/watch?v=ZTgfXSbGDBU&t=264s

**Comment by gtaylormb** [comment]
Any chance you can record a .dro file in dosbox/dosbox-x? That would really accelerate the debugging effort for me.

**Comment by gtaylormb** [comment]
One other thing--make sure you're using the latest unstable nightly build. There have been some fixes that have not yet made it into the latest stable release.

**Comment by hubby4** [comment]
I used the latest 06-09-24 unstable build.

The DRO is attached.

[monkey_000.zip](https://github.com/user-attachments/files/15802227/monkey_000.zip)

**Comment by gtaylormb** [comment]
Thanks for that. I'm able to replicate it--it does sound different to the real OPL3. The door opening sounds like 2 clicks on the OPL3. The second click seems to match (as well as the door closing sound), but the envelope on the first click for OPL3_FPGA seems to last about twice as long and kind of goes into an unmodulated sine wave the second half.

Retrowave OPL3 on DosBox-X:
![image](https://github.com/gtaylormb/opl3_fpga/assets/3758121/377820d3-b50d-4dae-a98f-cbaef166a8e4)


OPL3_FPGA on ao486_MiSTer:
![image](https://github.com/gtaylormb/opl3_fpga/assets/3758121/79ce9d5e-e1ce-4044-9bfb-978e2decea72)

My guess is there's something up with the envelope and it should have released much sooner. I'll dig into it.

**Comment by gtaylormb** [comment]
@hubby4 thank you for this testcase! This wins the prize for hardest bug to find. Will be PRing into ao486.
